### PR TITLE
[ADD] French Canadian Provinces

### PR DESCRIPTION
**Pull request by xerc**
https://fr.wikipedia.org/wiki/Provinces_et_territoires_du_Canada#Les_dix_provinces_et_les_trois_territoires

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Thank you for the pull request. We use for additional language an own directory would in your case be `subdivisions/ca/fr.json`, do you want to adjust it?

**Comment by xerc** [comment]
its not realy additional it is the second offical therefore i used the templates with the inline-names ..
https://github.com/alexander-schranz/iso-3166-2/blob/master/subdivisions/ar.json#L7
https://github.com/alexander-schranz/iso-3166-2/blob/master/subdivisions/br.json
https://github.com/alexander-schranz/iso-3166-2/blob/master/subdivisions/ua.json#L14
https://github.com/alexander-schranz/iso-3166-2/blob/master/subdivisions/uy.json#L13

**Comment by xerc** [comment]
but if you want to have it seperate.. voilà ; https://github.com/alexander-schranz/iso-3166-2/compare/master...xerc:ca-french
regex after duplication the other 4 within sub-folder; `(?<=: ").+?! `

**Comment by alexander-schranz** [comment]
I see. Thank you for your contribution!

**Comment by alexander-schranz** [comment]
Tagged as [v1.0.2](https://github.com/alexander-schranz/iso-3166-2/releases/tag/v1.0.2)

**Pull request merged**
